document.write('<script src="https://caksup.github.io/nulisaksarajawa/az/css.js"></script>')
document.write('<link rel="stylesheet" href="https://caksup.github.io/nulisaksarajawa/css/bootstrap/4.4.1/bootstrap.min.css">')
document.write('<link rel="stylesheet" href="https://caksup.github.io/nulisaksarajawa/css/cs/gayane.css">')
document.write('<link rel="stylesheet" href="https://caksup.github.io/nulisaksarajawa/css/naj/specimen_stylesheet.css" type="text/css" charset="utf-8" />')
document.write('<link rel="stylesheet" href="https://caksup.github.io/nulisaksarajawa/css/naj/stylesheet.css" type="text/css" charset="utf-8" />')
